/**
 * api/load.js — Vercel Serverless Function
 *
 * GET /api/load?code=P-X7K9
 *
 * Looks up the short_code in the Supabase packs table and returns the stored
 * pack_data JSON.  Returns 404 when the code is not found.
 *
 * Env vars required:
 *   SUPABASE_URL
 *   NEXT_PUBLIC_SUPABASE_ANON_KEY
 */

import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
);

// Matches the format generated by api/save.js — one char, dash, four chars.
// Allowed chars: A-Z (minus I/O) + 2-9 (minus 0/1).
const CODE_RE = /^[A-HJ-NP-Z2-9]-[A-HJ-NP-Z2-9]{4}$/;

export default async function handler(req, res) {
  if (req.method !== 'GET') {
    res.setHeader('Allow', 'GET');
    return res.status(405).json({ error: 'Method Not Allowed' });
  }

  const { code } = req.query;

  if (!code || typeof code !== 'string') {
    return res.status(400).json({ error: 'Missing required query parameter: code' });
  }

  // Normalise: strip surrounding whitespace, upper-case
  const normalised = code.trim().toUpperCase();

  if (!CODE_RE.test(normalised)) {
    return res.status(400).json({ error: 'Invalid code format. Expected format: X-XXXX (e.g. P-X7K9).' });
  }

  const { data, error } = await supabase
    .from('packs')
    .select('pack_data')
    .eq('short_code', normalised)
    .single();

  if (error || !data) {
    // PostgREST returns code PGRST116 when .single() finds no rows
    if (!data || error?.code === 'PGRST116') {
      return res.status(404).json({ error: `No pack found with code "${normalised}".` });
    }
    console.error('[api/load] Supabase select error:', error);
    return res.status(500).json({ error: 'Database error. Please try again.' });
  }

  return res.status(200).json(data.pack_data);
}
